### ISSUE TITLE
Disable Kibana Search Guard plugin

### ISSUE THREAD

**Issue by ayseyo** [floragunncom/search-guard-kibana-plugin#41]
Hi, is there an option to disable search guard kibana plugin as well?

I want to enable/disable SG kibana plugin to investigate performance issues. 

I know there is for SG elasticsearch plugin which can be used as : 

`searchguard.disabled: true`

I've tried this option at kibana.yml bu I got this error :

FATAL { ValidationError: child "searchguard" fails because ["disabled" is not allowed]
    at Object.exports.process (/usr/share/kibana/node_modules/joi/lib/errors.js:140:17)
    at internals.Any._validateWithOptions (/usr/share/kibana/node_modules/joi/lib/any.js:649:25)
    at root.validate (/usr/share/kibana/node_modules/joi/lib/index.js:102:23)
    at Config._commit (/usr/share/kibana/src/server/config/config.js:113:35)
    at Config.set (/usr/share/kibana/src/server/config/config.js:84:10)
    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:57:10)
    at /usr/share/kibana/src/server/plugins/plugin_collection.js:19:12
    at next (native)
    at step (/usr/share/kibana/src/server/plugins/plugin_collection.js:49:191)
    at /usr/share/kibana/src/server/plugins/plugin_collection.js:49:361
  name: 'ValidationError',

**Comment by ayseyo** [comment]
I guess this question is more appropriate for search guard community forum, sorry for the inconvenience, I'm closing this.
